management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: always
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - modulith

inventory:
  threshold: 10