management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  info:
    process:
      enabled: true

inventory:
  threshold: 10
spring:
  threads:
    virtual:
      enabled: true